name: Forked ci
on:
  push:
  workflow_dispatch:
  pull_request:
jobs:
  macos-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Test Swift Package macOS"
        run: swift test
      - name: "Test Swift Package iOS"
        run: xcodebuild test -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPhone 16" -scheme "Forked-Package"
  linux-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Test Swift Package on Linux"
        run: swift test
      - name: "Test Swift Package on Android"
        uses: skiptools/swift-android-action@v2
        with:
          run-tests: false
  windows:
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-6.0.3-release
          tag: 6.0.3-RELEASE
      - uses: actions/checkout@v4
      - name: "Test Swift Package on Windows"
        run: swift test

